name: Docker Arch - Complex PHP Project
services:
    # PHP Container
  - type: php
    path: ../app
    options:
        version: "7.1"
        cli_only: true
        zsh: true
        custom_zsh: true
        powerline: true
        composer: true
        extensions:
            - gd
        config:
            phar.readonly: 0
            memory_limit: 512M
