name: Docker Arch
services:
    # PHP Container
  - type: php
    path: ../
    container:
        packages:
            - make
            - libxslt-dev
    options:
        version: "7.1"
        cli_only: true
        zsh: true
        custom_zsh: true
        dotfiles: true
        composer: true
        extensions:
            - xsl
        config:
            phar.readonly: 0
