name: Docker Arch
services:
    # PHP Container
  - type: php
    path: ../
    container:
        packages:
            - make
            - libxslt-dev
        commands:
            - echo "alias docker-arch=\"/apps/php/bin/docker-arch generate\"" >> ~/.zshrc
    options:
        version: "7.1"
        cli: true
        zsh: true
        custom_zsh: true
        dotfiles: true
        composer: true
        extensions:
            - xsl
        config:
            phar.readonly: 0
