name: Docker Arch - PHP/MySQL Project
services:
    # Nginx Container
  - type: nginx
    path: ../app
    host: localhost
    # PHP Container
  - type: php
    path: ../app
    host: localhost
    options:
        version: "7.1"
        extensions:
            - pdo_mysql
    # MySQL Container
  - type: mysql
    options:
        version: "5.7"
