name: Docker Arch - PHP Node Project
services:
    # Nginx Container
  - type: nginx
    path: ../app
    host: localhost
    # PHP Node Container
  - type: phpNode
    path: ../app
    host: localhost
    options:
        version: "7.1"
