name: Docker Arch - PHP Redis Project
services:
    # Nginx Container
  - type: nginx
    path: ../app
    host: localhost
    # PHP Container
  - type: php
    path: ../app
    host: localhost
    options:
        version: "7.1"
        extensions:
            - redis
    container:
        volumes:
            - "../docker:/docker:ro"
        entry_point: ["/docker/php/entrypoint.sh"]
    # Redis Container
  - type: redis
