name: Docker Arch - Custom Image Project
services:
    # SFTP Container (connect from `sftp -P 2222 docker-arch@localhost`, password: unicorn)
  - type: custom
    identifier: sftp
    options:
        image: "atmoz/sftp:alpine"
        package_manager: apk
        cli: true
    container:
        cmd:
            - "docker-arch:unicorn:1001"
        ports:
            - "${SFTP_PORT:-2222}:22"
