name: Docker Arch - PHP ElasticSearch Project
services:
    # Nginx Container
  - type: nginx
    path: ../app
    host: localhost
    # PHP Container
  - type: php
    path: ../app
    host: localhost
    options:
        version: "7.1"
        extensions:
            - bcmath
    container:
        volumes:
            - "../docker:/docker:ro"
        entry_point: ["/bin/sh /docker/php/entrypoint.sh"]
    # ElasticSearch Container
  - type: elasticsearch
    options:
        version: "5.6"
